var a = new Int32Array([1, 2, 3, 4, 5]);
print(a.subarray().toString() === '1,2,3,4,5');
print(a.subarray(3).toString() === '4,5');
print(a.subarray(1, 3).toString() === '2,3');
print(a.subarray(-3).toString() === '3,4,5');
print(a.subarray(-3, -1).toString() === '3,4');
print(a.subarray(3, 2).toString() === '');
print(a.subarray(-2, -3).toString() === '');
print(a.subarray(4, 1).toString() === '');
print(a.subarray(-1, -4).toString() === '');
print(a.subarray(1).subarray(1).toString() === '3,4,5');
print(a.subarray(1, 4).subarray(1, 2).toString() === '3');
var b = new Uint8Array([]);
print(b.subarray(123456, -123456).toString() === '');
print(b.subarray().subarray().toString() === '');
var ab = new ArrayBuffer(28);
var tmp = new Int32Array(ab);
tmp.set([0, 1, 2, 3, 4, 5, 0]);
var c = new Int32Array(ab, 4, 5);
print(c.toString() === '1,2,3,4,5');
print(c.subarray().toString() === '1,2,3,4,5');
print(c.subarray(3).toString() === '4,5');
print(c.subarray(1, 3).toString() === '2,3');
print(c.subarray(-3).toString() === '3,4,5');
print(c.subarray(-3, -1).toString() === '3,4');
print(c.subarray(3, 2).toString() === '');
print(c.subarray(-2, -3).toString() === '');
print(c.subarray(4, 1).toString() === '');
print(c.subarray(-1, -4).toString() === '');
print(c.subarray(1).subarray(1).toString() === '3,4,5');
print(c.subarray(1, 4).subarray(1, 2).toString() === '3');